
---
- name: Copy zip folder to instance
  become: true
  copy:
    src: ./artifact.tar.gz
    dest: .

- name: Extract zip folder
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ./project

- name: "Install pm2"
  become: true
  shell: |
    cd project
    npm install
    pm2 stop default
    pm2 start npm -- start
