
---
- name: Copy zip folder to instance
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Extract zip folder
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Install pm2"
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start
